import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createServer as createHttpServer} from 'node:http';
import {createServer} from 'vite';
import {Window} from 'happy-dom';
const server=await createServer({optimizeDeps:{noDiscovery:true,include:[]},server:{middlewareMode:true,watch:null,hmr:{server:createHttpServer()}}});
const {parseRedditFeed,fetchRedditFeed}=await server.ssrLoadModule('/src/reddit-feed.ts');
await server.close();
const win=new Window();
const setup=t=>{for(const key of ['DOMParser','document','Element']){const old=globalThis[key];globalThis[key]=win[key];t.after(()=>{if(old===undefined)delete globalThis[key];else globalThis[key]=old;});}};
const post=`<entry><id>t3_abc</id><title>Example &amp; title</title><author><name>/u/person</name></author><link href="https://www.reddit.com/r/test/comments/abc/example/"/><content type="html">&lt;a href="https://example.com/story"&gt;[link]&lt;/a&gt;</content></entry>`;
const comment=`<entry><id>t1_def</id><author><name>/u/reply</name></author><link href="https://www.reddit.com/r/test/comments/abc/example/def/"/><content type="html">&lt;div class="md"&gt;&lt;p&gt;First paragraph.&lt;/p&gt;&lt;p&gt;Second &amp;amp; last. &lt;a href="https://example.com/proof"&gt;Evidence&lt;/a&gt;&lt;script&gt;bad()&lt;/script&gt;&lt;/p&gt;&lt;/div&gt;</content></entry>`;
const feed=entries=>`<feed xmlns="http://www.w3.org/2005/Atom"><category term="test"/>${entries}</feed>`;
test('public feed retains post links without inventing scores or counts',t=>{setup(t);const data=parseRedditFeed(feed(post),'https://www.reddit.com/r/test.json');assert.equal(data.posts[0].title,'Example & title');assert.equal(data.posts[0].url,'https://example.com/story');assert.equal(data.posts[0].permalink,'/r/test/comments/abc/example/');assert.equal(data.posts[0].score,undefined);assert.equal(data.posts[0].commentCount,undefined);});
test('discussion feed retains comment paragraphs and references as inert text',t=>{setup(t);const data=parseRedditFeed(feed(post+comment),'https://www.reddit.com/r/test/comments/abc/example/.json');assert.equal(data.type,'post_with_comments');assert.equal(data.comments[0].body,'First paragraph.\nSecond & last. Evidence');assert.equal(data.comments[0].links[0].url,'https://example.com/proof');assert.doesNotMatch(JSON.stringify(data),/bad\(\)/);});
test('feed rejects HTML, doctypes, oversize data and missing discussion posts',t=>{setup(t);for(const xml of ['<html>blocked</html>','<!DOCTYPE feed>'+feed(post),'a'.repeat(2*1024*1024+1),feed(comment)])assert.throws(()=>parseRedditFeed(xml,'https://www.reddit.com/r/test/comments/abc/example.json'));});
test('Reddit transport uses the relay without credentials and preserves rate-limit failures',async t=>{setup(t);let status=200;t.mock.method(globalThis,'fetch',async(url,init)=>{assert.match(url,/modal\.run\/reddit\?url=/);assert.equal(init.credentials,'omit');assert.ok(init.signal);return new Response(feed(post),{status});});assert.equal((await fetchRedditFeed('https://www.reddit.com/r/test.json')).posts.length,1);status=429;await assert.rejects(()=>fetchRedditFeed('https://www.reddit.com/r/test.json'),/rate limiting/);});
test('discussion identity must match the requested post',t=>{setup(t);assert.throws(()=>parseRedditFeed(feed(post+comment),'https://www.reddit.com/r/test/comments/other/example.json'),/requested post/);});
test('relative discussion references retain absolute navigation targets',t=>{setup(t);const xml=feed(post+comment.replace('https://example.com/proof','/r/test/comments/linked/title/'));const data=parseRedditFeed(xml,'https://www.reddit.com/r/test/comments/abc/example.json');assert.equal(data.comments[0].links[0].url,'https://www.reddit.com/r/test/comments/linked/title/');});
